spring.application.name=workouttracker
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=postgres
spring.datasource.password=postgres
